### ISSUE TITLE
Very nice program for learning BIOS

### ISSUE THREAD

**Issue by Nick-Vinesmoke** [GendalfBlack/GB-BIOS-Sim#1]
But i found some bugs in changing values.
_Take into account_ㄟ(≧◇≦)ㄏ

**Comment by GendalfBlack** [comment]
Thanks for comment! This is not even close a finished program, abandoned
project that waits to be reborn and refactored with all stuff I learned
over this years. Hope I'll find time soon, thanks for comment again!

вт, 7 лют. 2023, 19:20 користувач Nick Vinesmoke ***@***.***>
пише:
